# Generated by Django 4.2 on 2024-09-11 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webapp', '0004_alter_usuariocargounidad_fecha_inicio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('optimo', 'Óptimo'), ('bueno', 'Bueno'), ('regular', 'Regular'), ('algo_dañado', 'Algo Dañado'), ('malo', 'Malo')], max_length=50)),
                ('numero_hojas', models.IntegerField()),
                ('tipo_documentacion', models.CharField(max_length=100)),
                ('ambiente', models.CharField(max_length=100)),
                ('estante', models.CharField(max_length=100)),
                ('columna', models.CharField(max_length=100)),
                ('balda', models.CharField(max_length=100)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('responsable', models.CharField(blank=True, null=True)),
                ('tipo', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=100)),
                ('gestion', models.CharField(max_length=4)),
                ('secretaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.secretaria')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.unidad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
