# Generated by Django 4.2 on 2024-10-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userArchivoapp', '0002_prestamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='archivo_solicitud',
            field=models.FileField(blank=True, null=True, upload_to='solicitudes/'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='estado_solicitud',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10),
        ),
    ]
