# Generated by Django 4.2 on 2024-10-07 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userArchivoapp', '0003_prestamo_archivo_solicitud_prestamo_estado_solicitud'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='prestamo',
            table='nueva_tabla_prestamos',
        ),
    ]
