# Generated by Django 4.2 on 2024-10-07 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userArchivoapp', '0004_alter_prestamo_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='prestamo',
            table=None,
        ),
    ]
