# Generated by Django 4.2 on 2024-11-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userArchivoapp', '0006_gestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='fecha_documento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
