# Generated by Django 4.2 on 2024-12-05 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userArchivoapp', '0008_alter_documento_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='numero',
            field=models.CharField(max_length=100),
        ),
    ]
