# Generated by Django 4.2 on 2024-10-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_cargo_nombre_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='nombre_cargo',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='nombre_secretaria',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
