# Generated by Django 4.2 on 2024-10-06 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userArchivoapp', '0003_prestamo_archivo_solicitud_prestamo_estado_solicitud'),
        ('userPersonal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudprestamo',
            name='prestamo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userArchivoapp.prestamo'),
        ),
    ]
