# Generated by Django 4.2 on 2024-10-07 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userPersonal', '0002_solicitudprestamo_prestamo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudprestamo',
            name='prestamo',
        ),
    ]
