# Generated by Django 4.2 on 2024-10-07 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userArchivoapp', '0005_alter_prestamo_table'),
        ('userPersonal', '0003_remove_solicitudprestamo_prestamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudprestamo',
            name='prestamo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userArchivoapp.prestamo'),
        ),
    ]
